project_id = "xmrmkgfgpoundfwhnxfs"

[functions.scheduled-customer-sync]
verify_jwt = false

[functions.scheduled-order-sync]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.scheduled-recurring-invoice-sync]
verify_jwt = false

[functions.weekly-sync]
verify_jwt = false

[functions.create-full-backup]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.sync-backup-to-hetzner]
verify_jwt = false

[functions.nightly-backup]
verify_jwt = false

[functions.test-import-eu2]
verify_jwt = false

[functions.import-all-items-eu2]
verify_jwt = false






