// Weltweite Ländervorwahlen für die Premium-Beratung.
// Gruppe 1: EU (+EFTA/UK), Gruppe 2: Rest der Welt.

export type CountryCode = {
  code: string;
  flag: string;
  label: string;
  min?: number;
  max?: number;
};

export const CUSTOM_CODE = '__custom__';

export const EU_CODES: CountryCode[] = [
  { code: '+49', flag: '🇩🇪', label: 'Deutschland', min: 9, max: 13 },
  { code: '+43', flag: '🇦🇹', label: 'Österreich', min: 8, max: 13 },
  { code: '+41', flag: '🇨🇭', label: 'Schweiz', min: 8, max: 12 },
  { code: '+32', flag: '🇧🇪', label: 'Belgien', min: 8, max: 11 },
  { code: '+359', flag: '🇧🇬', label: 'Bulgarien', min: 8, max: 10 },
  { code: '+45', flag: '🇩🇰', label: 'Dänemark', min: 8, max: 10 },
  { code: '+372', flag: '🇪🇪', label: 'Estland', min: 7, max: 10 },
  { code: '+358', flag: '🇫🇮', label: 'Finnland', min: 7, max: 11 },
  { code: '+33', flag: '🇫🇷', label: 'Frankreich', min: 9, max: 11 },
  { code: '+30', flag: '🇬🇷', label: 'Griechenland', min: 10, max: 11 },
  { code: '+44', flag: '🇬🇧', label: 'Großbritannien', min: 9, max: 11 },
  { code: '+353', flag: '🇮🇪', label: 'Irland', min: 8, max: 11 },
  { code: '+354', flag: '🇮🇸', label: 'Island', min: 7, max: 9 },
  { code: '+39', flag: '🇮🇹', label: 'Italien', min: 8, max: 13 },
  { code: '+385', flag: '🇭🇷', label: 'Kroatien', min: 8, max: 10 },
  { code: '+371', flag: '🇱🇻', label: 'Lettland', min: 8, max: 9 },
  { code: '+423', flag: '🇱🇮', label: 'Liechtenstein', min: 7, max: 9 },
  { code: '+370', flag: '🇱🇹', label: 'Litauen', min: 8, max: 9 },
  { code: '+352', flag: '🇱🇺', label: 'Luxemburg', min: 6, max: 11 },
  { code: '+356', flag: '🇲🇹', label: 'Malta', min: 8, max: 8 },
  { code: '+31', flag: '🇳🇱', label: 'Niederlande', min: 9, max: 11 },
  { code: '+47', flag: '🇳🇴', label: 'Norwegen', min: 8, max: 10 },
  { code: '+48', flag: '🇵🇱', label: 'Polen', min: 9, max: 11 },
  { code: '+351', flag: '🇵🇹', label: 'Portugal', min: 9, max: 11 },
  { code: '+40', flag: '🇷🇴', label: 'Rumänien', min: 9, max: 10 },
  { code: '+46', flag: '🇸🇪', label: 'Schweden', min: 7, max: 11 },
  { code: '+421', flag: '🇸🇰', label: 'Slowakei', min: 9, max: 9 },
  { code: '+386', flag: '🇸🇮', label: 'Slowenien', min: 8, max: 9 },
  { code: '+34', flag: '🇪🇸', label: 'Spanien', min: 9, max: 11 },
  { code: '+420', flag: '🇨🇿', label: 'Tschechien', min: 9, max: 10 },
  { code: '+36', flag: '🇭🇺', label: 'Ungarn', min: 8, max: 10 },
  { code: '+357', flag: '🇨🇾', label: 'Zypern', min: 8, max: 8 },
];

export const WORLD_CODES: CountryCode[] = [
  { code: '+93', flag: '🇦🇫', label: 'Afghanistan' },
  { code: '+20', flag: '🇪🇬', label: 'Ägypten' },
  { code: '+355', flag: '🇦🇱', label: 'Albanien' },
  { code: '+213', flag: '🇩🇿', label: 'Algerien' },
  { code: '+376', flag: '🇦🇩', label: 'Andorra' },
  { code: '+244', flag: '🇦🇴', label: 'Angola' },
  { code: '+54', flag: '🇦🇷', label: 'Argentinien' },
  { code: '+374', flag: '🇦🇲', label: 'Armenien' },
  { code: '+994', flag: '🇦🇿', label: 'Aserbaidschan' },
  { code: '+251', flag: '🇪🇹', label: 'Äthiopien' },
  { code: '+61', flag: '🇦🇺', label: 'Australien' },
  { code: '+973', flag: '🇧🇭', label: 'Bahrain' },
  { code: '+880', flag: '🇧🇩', label: 'Bangladesch' },
  { code: '+375', flag: '🇧🇾', label: 'Belarus' },
  { code: '+229', flag: '🇧🇯', label: 'Benin' },
  { code: '+591', flag: '🇧🇴', label: 'Bolivien' },
  { code: '+387', flag: '🇧🇦', label: 'Bosnien und Herzegowina' },
  { code: '+267', flag: '🇧🇼', label: 'Botswana' },
  { code: '+55', flag: '🇧🇷', label: 'Brasilien' },
  { code: '+673', flag: '🇧🇳', label: 'Brunei' },
  { code: '+226', flag: '🇧🇫', label: 'Burkina Faso' },
  { code: '+56', flag: '🇨🇱', label: 'Chile' },
  { code: '+86', flag: '🇨🇳', label: 'China' },
  { code: '+506', flag: '🇨🇷', label: 'Costa Rica' },
  { code: '+225', flag: '🇨🇮', label: "Côte d'Ivoire" },
  { code: '+1809', flag: '🇩🇴', label: 'Dominikanische Republik' },
  { code: '+593', flag: '🇪🇨', label: 'Ecuador' },
  { code: '+503', flag: '🇸🇻', label: 'El Salvador' },
  { code: '+291', flag: '🇪🇷', label: 'Eritrea' },
  { code: '+679', flag: '🇫🇯', label: 'Fidschi' },
  { code: '+241', flag: '🇬🇦', label: 'Gabun' },
  { code: '+220', flag: '🇬🇲', label: 'Gambia' },
  { code: '+995', flag: '🇬🇪', label: 'Georgien' },
  { code: '+233', flag: '🇬🇭', label: 'Ghana' },
  { code: '+502', flag: '🇬🇹', label: 'Guatemala' },
  { code: '+224', flag: '🇬🇳', label: 'Guinea' },
  { code: '+509', flag: '🇭🇹', label: 'Haiti' },
  { code: '+504', flag: '🇭🇳', label: 'Honduras' },
  { code: '+852', flag: '🇭🇰', label: 'Hongkong' },
  { code: '+91', flag: '🇮🇳', label: 'Indien' },
  { code: '+62', flag: '🇮🇩', label: 'Indonesien' },
  { code: '+964', flag: '🇮🇶', label: 'Irak' },
  { code: '+98', flag: '🇮🇷', label: 'Iran' },
  { code: '+972', flag: '🇮🇱', label: 'Israel' },
  { code: '+81', flag: '🇯🇵', label: 'Japan' },
  { code: '+967', flag: '🇾🇪', label: 'Jemen' },
  { code: '+962', flag: '🇯🇴', label: 'Jordanien' },
  { code: '+855', flag: '🇰🇭', label: 'Kambodscha' },
  { code: '+237', flag: '🇨🇲', label: 'Kamerun' },
  { code: '+1', flag: '🇨🇦', label: 'Kanada' },
  { code: '+7', flag: '🇰🇿', label: 'Kasachstan' },
  { code: '+974', flag: '🇶🇦', label: 'Katar' },
  { code: '+254', flag: '🇰🇪', label: 'Kenia' },
  { code: '+996', flag: '🇰🇬', label: 'Kirgisistan' },
  { code: '+57', flag: '🇨🇴', label: 'Kolumbien' },
  { code: '+243', flag: '🇨🇩', label: 'Kongo (Dem. Rep.)' },
  { code: '+383', flag: '🇽🇰', label: 'Kosovo' },
  { code: '+53', flag: '🇨🇺', label: 'Kuba' },
  { code: '+965', flag: '🇰🇼', label: 'Kuwait' },
  { code: '+856', flag: '🇱🇦', label: 'Laos' },
  { code: '+266', flag: '🇱🇸', label: 'Lesotho' },
  { code: '+961', flag: '🇱🇧', label: 'Libanon' },
  { code: '+231', flag: '🇱🇷', label: 'Liberia' },
  { code: '+218', flag: '🇱🇾', label: 'Libyen' },
  { code: '+261', flag: '🇲🇬', label: 'Madagaskar' },
  { code: '+265', flag: '🇲🇼', label: 'Malawi' },
  { code: '+60', flag: '🇲🇾', label: 'Malaysia' },
  { code: '+960', flag: '🇲🇻', label: 'Malediven' },
  { code: '+223', flag: '🇲🇱', label: 'Mali' },
  { code: '+212', flag: '🇲🇦', label: 'Marokko' },
  { code: '+222', flag: '🇲🇷', label: 'Mauretanien' },
  { code: '+230', flag: '🇲🇺', label: 'Mauritius' },
  { code: '+389', flag: '🇲🇰', label: 'Nordmazedonien' },
  { code: '+52', flag: '🇲🇽', label: 'Mexiko' },
  { code: '+373', flag: '🇲🇩', label: 'Moldau' },
  { code: '+377', flag: '🇲🇨', label: 'Monaco' },
  { code: '+976', flag: '🇲🇳', label: 'Mongolei' },
  { code: '+382', flag: '🇲🇪', label: 'Montenegro' },
  { code: '+258', flag: '🇲🇿', label: 'Mosambik' },
  { code: '+95', flag: '🇲🇲', label: 'Myanmar' },
  { code: '+264', flag: '🇳🇦', label: 'Namibia' },
  { code: '+977', flag: '🇳🇵', label: 'Nepal' },
  { code: '+64', flag: '🇳🇿', label: 'Neuseeland' },
  { code: '+505', flag: '🇳🇮', label: 'Nicaragua' },
  { code: '+227', flag: '🇳🇪', label: 'Niger' },
  { code: '+234', flag: '🇳🇬', label: 'Nigeria' },
  { code: '+968', flag: '🇴🇲', label: 'Oman' },
  { code: '+92', flag: '🇵🇰', label: 'Pakistan' },
  { code: '+970', flag: '🇵🇸', label: 'Palästina' },
  { code: '+507', flag: '🇵🇦', label: 'Panama' },
  { code: '+675', flag: '🇵🇬', label: 'Papua-Neuguinea' },
  { code: '+595', flag: '🇵🇾', label: 'Paraguay' },
  { code: '+51', flag: '🇵🇪', label: 'Peru' },
  { code: '+63', flag: '🇵🇭', label: 'Philippinen' },
  { code: '+250', flag: '🇷🇼', label: 'Ruanda' },
  { code: '+7', flag: '🇷🇺', label: 'Russland' },
  { code: '+966', flag: '🇸🇦', label: 'Saudi-Arabien' },
  { code: '+221', flag: '🇸🇳', label: 'Senegal' },
  { code: '+381', flag: '🇷🇸', label: 'Serbien' },
  { code: '+248', flag: '🇸🇨', label: 'Seychellen' },
  { code: '+232', flag: '🇸🇱', label: 'Sierra Leone' },
  { code: '+263', flag: '🇿🇼', label: 'Simbabwe' },
  { code: '+65', flag: '🇸🇬', label: 'Singapur' },
  { code: '+252', flag: '🇸🇴', label: 'Somalia' },
  { code: '+94', flag: '🇱🇰', label: 'Sri Lanka' },
  { code: '+27', flag: '🇿🇦', label: 'Südafrika' },
  { code: '+249', flag: '🇸🇩', label: 'Sudan' },
  { code: '+82', flag: '🇰🇷', label: 'Südkorea' },
  { code: '+963', flag: '🇸🇾', label: 'Syrien' },
  { code: '+992', flag: '🇹🇯', label: 'Tadschikistan' },
  { code: '+886', flag: '🇹🇼', label: 'Taiwan' },
  { code: '+255', flag: '🇹🇿', label: 'Tansania' },
  { code: '+66', flag: '🇹🇭', label: 'Thailand' },
  { code: '+228', flag: '🇹🇬', label: 'Togo' },
  { code: '+1868', flag: '🇹🇹', label: 'Trinidad und Tobago' },
  { code: '+216', flag: '🇹🇳', label: 'Tunesien' },
  { code: '+90', flag: '🇹🇷', label: 'Türkei' },
  { code: '+993', flag: '🇹🇲', label: 'Turkmenistan' },
  { code: '+256', flag: '🇺🇬', label: 'Uganda' },
  { code: '+380', flag: '🇺🇦', label: 'Ukraine' },
  { code: '+598', flag: '🇺🇾', label: 'Uruguay' },
  { code: '+1', flag: '🇺🇸', label: 'USA' },
  { code: '+998', flag: '🇺🇿', label: 'Usbekistan' },
  { code: '+58', flag: '🇻🇪', label: 'Venezuela' },
  { code: '+971', flag: '🇦🇪', label: 'Vereinigte Arabische Emirate' },
  { code: '+84', flag: '🇻🇳', label: 'Vietnam' },
  { code: '+260', flag: '🇿🇲', label: 'Sambia' },
];

export const ALL_COUNTRY_CODES: CountryCode[] = [...EU_CODES, ...WORLD_CODES];

export function findCountry(code: string): CountryCode | undefined {
  return ALL_COUNTRY_CODES.find((c) => c.code === code);
}
