DELETE FROM workspace_nav_items WHERE workspace_id='4acf870d-fafc-4674-b424-cd45b4dbb005';
INSERT INTO workspace_nav_items (workspace_id,label,path,icon,section,roles,sort_order,is_active)
SELECT '4acf870d-fafc-4674-b424-cd45b4dbb005'::uuid, v.label, v.path, v.icon, (ARRAY['DASHBOARD','ANZAHLUNGEN','RECHNUNGEN','RATENZAHLER','RATENZAHLER · FREMD LEASING','MAHNUNGEN','KASSENBUCH & JOURNAL','PROVISION MITARBEITER','ANWALTSFÄLLE','STATISTIK','BANK & KONTOAUSZÜGE'])[v.si+1], CASE v.rc WHEN 'A' THEN ARRAY['Admin','Super Admin'] WHEN 'C' THEN ARRAY['Admin','Super Admin','Buchhaltung CH'] ELSE ARRAY['Admin','Super Admin','Buchhaltung Admin','Buchhaltung EU','Buchhaltung CH'] END, v.ord, true
FROM (VALUES
('Dashboard','/finance/dashboard','Banknote',0,'A',1),
('Finance Cockpit','/finance/cockpit','Banknote',0,'A',2),
('Controlling-Cockpit','/finance/controlling','Activity',0,'A',3),
('Offene Anzahlungen','/finance/offene-anzahlungen','Wallet',1,'A',4),
('Rechnungen','/finance/rechnungen','FileText',2,'A',5),
('Mietkauf Geräte','/finance/vermietung','Repeat',2,'A',6),
('Rechnungsvorschläge (Reparaturen)','/finance/rechnungsvorschlaege','Banknote',2,'A',7),
('Offene Posten','/finance/offene-posten','FileText',2,'A',8),
('Zahlungen','/finance/zahlungen','Banknote',2,'A',9),
('Gutschriften','/verkauf/gutschriften','Undo2',2,'A',10),
('Eingangsrechnungen','/finance/eingangsrechnungen','Inbox',2,'A',11),
('Belegarchiv','/finance/belege','Files',2,'A',12),
('Procure-to-Pay','/finance/p2p','FileText',2,'A',13),
('Bankimport','/finance/bank','Banknote',2,'A',14),
('SEPA Lastschriften','/finance/sepa','Banknote',2,'A',15),
('QR-Rechnung 🇨🇭','/finance/qr-rechnung','Banknote',2,'C',16),
('CH Lastschriften (LSV+/BDD) 🇨🇭','/finance/ch-lastschriften','Banknote',2,'C',17),
('CAMT.054 Import 🇨🇭','/finance/camt054','Banknote',2,'C',18),
('Bank-Abgleich 🇨🇭','/finance/bank-abgleich-ch','Banknote',2,'C',19),
('Treasury','/finance/treasury','Banknote',2,'A',20),
('Wiederkehrende Zahler','/finance/wiederkehrende-zahler','Repeat',3,'A',21),
('Bestandsübersicht','/finance/bestandsuebersicht','Repeat',3,'A',22),
('PRÜFUNG','/finance/vertraege','FileText',3,'A',23),
('Laufende Raten','/finance/raten','ScrollText',3,'A',24),
('Ratenplan synchronisieren','/finance/ratenplan-sync','Repeat',3,'A',25),
('SEPA MANDAT','/finance/alix-flex','Banknote',3,'A',26),
('Verfügbare Aufträge','/finanzierungen/leasing-bank','Landmark',4,'A',27),
('Finanzierung beantragen','/finanzierungen/beantragen','FileSignature',4,'A',28),
('Anfragen offen','/finanzierungen/anfragen-offen','Clock',4,'A',29),
('Zusagen Bank','/finanzierungen/zusagen-bank','CheckCircle2',4,'A',30),
('Absagen Bank','/finanzierungen/absagen-bank','X',4,'A',31),
('ALIX COLLECT','/finance/collect','AlertTriangle',5,'A',32),
('Prioritätenliste','/finance/collect/liste','FileText',5,'A',33),
('Aufgaben & Wiedervorlagen','/finance/collect/aufgaben','FileText',5,'A',34),
('Collect Auswertungen','/finance/collect/auswertungen','FileText',5,'A',35),
('Kreditlimits & Sperren','/finance/collect/limits','FileText',5,'A',36),
('Executive Cockpit','/finance/collect/cockpit','FileText',5,'A',37),
('Customer Health Score','/finance/collect/health','FileText',5,'A',38),
('Collections Playbooks','/finance/collect/playbooks','FileText',5,'A',39),
('Gebühren & Zinsen','/finance/collect/gebuehren','FileText',5,'A',40),
('Mahnstufen-Konfiguration','/finance/collect/einstellungen','FileText',5,'A',41),
('Verkäuferbewertung','/finance/collect/verkaeufer','FileText',5,'A',42),
('Governance & Freigaben','/finance/collect/freigaben','FileText',5,'A',43),
('Recht & Inkasso','/finance/collect/recht','FileText',5,'A',44),
('Geräte & Remote-Sperren','/finance/collect/geraete','FileText',5,'A',45),
('Digitale Akte','/finance/collect/akte','FileText',5,'A',46),
('Schriftverkehr & Zahl-Links','/finance/collect/schriftverkehr','FileText',5,'A',47),
('Finance AI','/finance/collect/copilot','FileText',5,'A',48),
('Mahnwesen','/finance/mahnwesen','FileText',5,'A',49),
('Kassenbuch','/finance/kassenbuch','BookOpen',6,'A',50),
('Buchungsjournal','/finance/buchungsjournal','ScrollText',6,'A',51),
('Zahlungsübersicht','/finance/zahlungsuebersicht','Wallet',6,'A',52),
('Bankbuchungen','/finance/bankbuchungen','Landmark',6,'A',53),
('Export DATEV','/finance/datev-export','FileDown',6,'A',54),
('Audit & Revision','/finance/audit-revision','ShieldCheck',6,'A',55),
('Stammdaten (Kontenrahmen · Perioden)','/finance/stammdaten','Database',6,'B',56),
('Übersicht','/finance/provision','BarChart3',7,'B',57),
('Offene Provisionen','/finance/provision/offene','Clock',7,'B',58),
('Freizugebende Provisionen','/finance/provision/freizugeben','Lock',7,'A',59),
('Freigegebene Provisionen','/finance/provision/freigegeben','CheckCircle2',7,'B',60),
('Auszahlungsübersicht','/finance/provision/auszahlungen','Banknote',7,'B',61),
('Stornierte Provisionen','/finance/provision/stornierte','X',7,'B',62),
('Provisionsabrechnungen','/finance/provision/abrechnungen','FileText',7,'B',63),
('Mitarbeiter-Zuordnung','/finance/provision/zuordnung','Users',7,'A',64),
('Provisionsregeln','/finance/provision/regeln','Database',7,'A',65),
('Auswertungen','/finance/provision/auswertungen','BarChart3',7,'B',66),
('Provisions-Audit','/finance/provision/audit','FileText',7,'A',67),
('Einstellungen','/finance/provision/einstellungen','Repeat',7,'A',68),
('Anwaltsfälle','/finance/anwaltsfaelle','Gavel',8,'B',69),
('Anlagenbuchhaltung','/finance/anlagen','FileText',9,'A',70),
('AfA-Lauf','/finance/anlagen/afa-lauf','FileText',9,'A',71),
('Anlagenspiegel & Inventar','/finance/anlagenspiegel','FileText',9,'A',72),
('BWA','/finance/bwa','BarChart3',9,'A',73),
('GuV','/finance/guv','FileText',9,'A',74),
('Bilanz','/finance/bilanz','FileText',9,'A',75),
('Jahresabschluss','/finance/jahresabschluss','Lock',9,'A',76),
('Periodenabschluss & Sperre','/finance/perioden','Lock',9,'B',77),
('DATEV','/finance/datev','FileText',9,'A',78),
('Steuer-Auswertung','/finance/steuer','FileText',9,'A',79),
('Steuer & Meldewesen','/finance/meldewesen','FileText',9,'A',80),
('Steuerkonto & Zahllast','/finance/steuerkonto','FileText',9,'A',81),
('Budgetplanung','/finance/budget','BarChart3',9,'A',82),
('Soll-Ist-Vergleich','/finance/soll-ist','TrendingUp',9,'A',83),
('Rolling Forecast','/finance/forecast','LineChart',9,'A',84),
('Kostenstellen-Report','/finance/kostenstellen-report','BarChart3',9,'B',85),
('Deckungsbeitrag DB1/DB2','/finance/deckungsbeitrag','TrendingUp',9,'B',86),
('Segmentbericht','/finance/segmentbericht','BarChart3',9,'B',87),
('Kontenblätter','/finance/kontenblaetter','FileText',9,'B',88),
('Saldenbilanz','/finance/saldenbilanz','BarChart3',9,'B',89),
('Revisionsexport','/finance/revisionsexport','FileText',9,'B',90),
('Lohnbuchhaltung & SV','/finance/lohnbuchhaltung','Users',9,'B',91),
('Liquiditätsplanung','/finance/liquiditaet','Banknote',9,'A',92),
('Konsolidierung','/finance/konsolidierung','BarChart3',9,'A',93),
('Intercompany','/finance/intercompany','Activity',9,'A',94),
('Devisenkurse','/finance/fx','Banknote',9,'A',95),
('Konzern-GuV (EU+CH)','/finance/konzern-guv','Globe2',9,'A',96),
('Konzern-Bilanz (EU+CH)','/finance/konzern-bilanz','Globe2',9,'A',97),
('AUSGELIEFERT · Faktura-Kontrolle','/finance/ausgeliefert','Truck',9,'B',98),
('KI-Analyse','/finance/ai-insights','Sparkles',9,'A',99),
('Anomalien','/finance/anomalien','AlertTriangle',9,'A',100),
('KI-Assistent (Fragen)','/finance/ask','MessageCircle',9,'A',101),
('Report Builder','/finance/reports','BarChart3',9,'A',102),
('Berichts-Zeitpläne','/finance/schedules','Activity',9,'A',103),
('Management-Pack','/finance/management-pack','FileText',9,'A',104),
('Stakeholder-Portale','/finance/stakeholders','Users',9,'A',105),
('Freigaben','/finance/freigaben','CheckSquare',9,'A',106),
('Automations','/finance/automations','Cog',9,'A',107),
('Compliance','/finance/compliance','BadgeCheck',9,'A',108),
('Systemstatus','/finance/einstellungen/systemstatus','FileText',9,'A',109),
('Kontoauszüge importieren','/finance/kontoauszuege/import','Landmark',10,'A',110),
('Importierte Buchungen','/finance/kontoauszuege/buchungen','Landmark',10,'A',111),
('Offene Zuordnungen','/finance/kontoauszuege/offen','Landmark',10,'A',112),
('Bereits verbuchte Zahlungen','/finance/kontoauszuege/verbucht','Landmark',10,'A',113),
('Importhistorie','/finance/kontoauszuege/historie','Landmark',10,'A',114),
('Rücklastschriftquote','/finance/kontoauszuege/quote','Landmark',10,'A',115),
('Bankkonten','/finance/kontoauszuege/konten','Landmark',10,'A',116),
('Importregeln','/finance/kontoauszuege/regeln','Landmark',10,'A',117),
('DATEV-Export','/finance/kontoauszuege/datev','Landmark',10,'A',118),
('Bank-API / EBICS','/finance/kontoauszuege/bank-api','Landmark',10,'A',119)
) AS v(label,path,icon,si,rc,ord);